spring:
  datasource:
    url: jdbc:mysql://localhost:3306/media_system
    username: root
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver

minio:
  endpoint: http://localhost:9000
  accessKey: your_access_key
  secretKey: your_secret_key
  bucket: media-files

server:
  port: 8080 

jwt:
  secret: your-secret-key
  expiration: 86400000 # 24小时 