spring:
  datasource:
    url: jdbc:mysql://1.94.109.12:3306/media_system
    username: root
    password: xxs@2024
    driver-class-name: com.mysql.cj.jdbc.Driver

minio:
  endpoint: http://1.94.109.12:9000
  accessKey: admin
  secretKey: password123
  bucket: media-files

server:
  port: 3335

jwt:
  secret: your-secret-key
  expiration: 86400000 # 24小时 